# Generated by Django 5.0.3 on 2024-03-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Structure',
            new_name='Construction',
        ),
    ]
