# Generated by Django 5.0.3 on 2024-03-16 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_server', '0004_alter_construction_order_alter_construction_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constructions', to='api_server.order'),
        ),
        migrations.AlterField(
            model_name='construction',
            name='windows',
            field=models.ManyToManyField(related_name='constructions', to='api_server.window'),
        ),
    ]
